### PR TITLE
Change the triangles to equilateral triangle based on a circle with given radius. Change size of diamonds to match area of square.

### PR DESCRIPTION
**Pull request by jonoyuan**
Currently, triangles are based on a unit square. To create an equilateral triangle that is visually a similar area as a square or circle marker, we use a triangle size that's halfway between a circumscribed triangle and an inscribed triangle around a unit circle.

image

### CODE REVIEW

**Comment by jonoyuan** [comment]
Added more commits changing diamonds to match squares visually.

**Comment by rowanwins** [comment]
Hi @jonoyuan 

Thanks for the work - although if you could make the changes in the `source` directory that would be awesome!

**Comment by jonoyuan** [comment]
@rowanwins done!

**Comment by rowanwins** [comment]
Released in v1.2.0 to npm

**Pull request merged**
