### PR TITLE
Fix square & diamonds

### PR DESCRIPTION
**Pull request by lerela**
Square & diamonds were failing on Firefox because of the svg syntax. Removing the commas fixed it.
minified version is slightly different, feel free to keep only the comma fixes

### CODE REVIEW

**Comment by rowanwins** [comment]
Thanks for the fix @lerela

**Comment by troglodito** [comment]
Thanks for your great work, @rowanwins!
I've just started using SvgShapeMarkers in our Angular project via the npm module.
Since we also use Firefox: Would it be possible to generate a new release with this fix and publish it to npm?

**Comment by rowanwins** [comment]
Hey @troglodito - just published as v`1.1.0` - thanks for the prompt!

**Comment by troglodito** [comment]
Thanks for the new release @rowanwins  - squares and diamonds are now OK on Firefox as expected.

**Pull request merged**
